### ISSUE TITLE
BiRatOK

### ISSUE THREAD

**Issue by violetteta8** [HydrodynamicsGroup/RDITemplate#2]
I noticed that the Bi-directional rating option only goes true if it's a ChannelMaster (2 beam system). 

  If (EX <= 15) AND (EX > 7) Then
    Coord = "INST"
    Select Case NumBeams
    Case 2
      Decode = "Instrument Coordinates - V1=X V2=Y disregard V3 and V4"
      BiRatOK = True 'sets flag indication that this is a channel master in instrument coordinates and it's ok to use a bi-directional rating if needed
    Case 3
      Decode = "Instrument Coordinates - V1=X V2=Y disregard V3 V4=Error"
    Case 4
      Decode = "Instrument Coordinates - V1=X V2=Y V3=Z and V4=Error"
    Case Else
      Decode = "System could not be decoded"
    End Select
    UseDir = False
 EndIf

Why can't 3-beam WH H-ADCPs have the option of the bi-directional rating?

**Comment by SimpsonMike** [comment]
I'm not sure where that code came from.  Possibly JB thought we would only use biratings with Channel masters.  I don't see why it should be limited, because bi-ratings can occur at any measurement site.
-Mik

**Comment by violetteta8** [comment]
Do you think we should limit to just systems with 3 beams though? I think it'd be unlikely to have a BiRating with a 4-beam system. Plus, we built in the auto-range for uplookers. (VADCP is obviously a different story as it has 3 beams, but we can right logic to disregard that system from the BiRating stuff)

**Comment by SimpsonMike** [comment]
If you don't think it's likely that we would be measuring discharge with a 4 beam system where the bins would need to be adjusted for differences in Ebb and Flood flows, then I think we could limit the BiRating code to just 3 beam systems (excluding the VADCP).

**Comment by violetteta8** [comment]
I'll just do that then. I chatted with Cathy about it. I don't think it'd be likely to want to switch bins with an uplooker, especially with the auto-ranging. We can still have a breakpoint rating if necessary, but that's already built in with the UpVel, LowVel stuff. I'll fix this real quick and pull it to the Master branch.

**Comment by violetteta8** [comment]
Should be all set now. Pulled to master.
